### ISSUE TITLE
[SDK BUG] App-to-App Communication Stops working occasionally

### ISSUE THREAD

**Issue by jurkog** [microsoft/XboxGameBarSamples#110]
**Describe the bug**
This might be a crapshoot but I'd love to hear your thoughts on areas that I should look into.

Occasionally, (we get one or two emails a day about this), users of the Crosshair X Extension can't connect the Desktop app to the Game Bar widget via the Named Pipes or AppServiceConnection protocol until they restart their PC. Although we've found a solution to temporarily make the problem go away (restarting the PC), it still creates a bad customer experience.

Given that I've tried both protocols and both seem to fail, I'm starting to wonder if there's an issue with UWP / Game Bar.

I've met with customers in Discord and did a thorough troubleshooting session with them. The users of the AppServiceConnection don't ever connect nor do they ever get an error. It's as if it's blocked or something.

**To Reproduce**
1. Download the Crosshair X app on the Microsoft Store or Steam
2. Download the Crosshair X Extension on the Game Bar
3. Eventually it'll bug out (sometimes two weeks after the user purchases it).
4. Crosshair Won't Update. It'll just say 'Run the Crosshair X Desktop App' indefinitely and they'll have to restart their PC

**Expected behavior**
Crosshair X connects to the Crosshair X Extension when they're both launched and the Crosshair updates.

**Screenshots**

**Desktop (please complete the following information):**
- OS version: Up to date versions of Win 10 and 11, I've asked customers to update and we use Sentry to verify this
- Game Bar version: Latest Versions, I've asked customers to update and this has been happening for a long time
- SDK version: Latest version

**Additional context**
I'm just stumped on this one and am hoping you guys have access to a subject matter expert that could at least point me in a new direction. Not sure if it's something I'm doing wrong as it's only an intermittent issue.

**Comment by totallymonkey** [comment]
Hi jurkog. I will follow up with others on the team to see if there are some additional troubleshooting steps we can provide.

**Comment by jurkog** [comment]
Sounds great.

Let me know if theres any other information I could provide. I'd even be willing to get on a call / instant messaging with someone from the team if that helps.

**Comment by vidager** [comment]
Hi Jurkog, do you know if these issues happen while your widget is pinned? From your description it sounds like this is hit on widget launch? We have a bug on Win11 systems where widgets are getting suspended if they're loaded but not pinned on the screen (when game bar is dismissed/pinnedonly mode).  This shouldn't affect your scenarios when your widget is pinned, but if the user didn't have it pinned, it would get suspended and then perhaps break your IPC synchronization. We're fixing this in 2207 release of Game Bar. You said the issue occurs on Win10 as well, so likely something else, but wanted to mention it regardless. 

In the cases where your widget can no longer communicate with your desktop app, have you confirmed your desktop app is still in a state where the server can be connected to?  The fact that you said the same problem happens for named pipes and AppServices has me stumped. If it was just one, we could pursue nuances with a given tech as a likely suspect, but with it happening with both, that's odd. Those two techs are quite different from each other under the covers. It could definitely be a Windows bug, but with the indicators you've given, I'd be leaning toward something problematic between your two processes that you control?

For app services we can reach out to the team to see if they have tracing that could assist you in your investigation. I doubt the named pipes would have anything there. Let me know if that would be a help to you!

Thank you, and sorry for the delay,
Ben

**Comment by jurkog** [comment]
Hi Ben,

Thank you for the detailed response!

"have you confirmed your desktop app is still in a state where the server can be connected to?"

This is what seems to have been the problem. The app seemed to just break out of a good state until the next restart. We believe we fixed this in our next update.

Thank you for the response and troubleshooting help!
