### ISSUE TITLE
Setting PinningSupported to false doesn't take the widget out of pinned mode

### ISSUE THREAD

**Issue by nathanAjacobs** [microsoft/XboxGameBarSamples#112]
Changing PinningSupported to false on a widget that is currently pinned state removes the pinning button for the widget, but does not take the widget out of pinned mode. Shouldn't it automatically take the widget out of pinned mode when setting PinningSupported to false?

**Comment by vidager** [comment]
Thank you for reporting. This is likely a bug. We'll investigate!

**Comment by vidager** [comment]
This was fixed in 2310 release of Game Bar
