### ISSUE TITLE
[QUESTION] Transparency in DirectX11

### ISSUE THREAD

**Issue by Spuckwaffel** [microsoft/XboxGameBarSamples#117]
hey there,
im trying to create a xbox gamebar widget using directx11. Im using sample code from visual studios directx 11 app sample. Everything works fine, however im unable to render anything transparent. ID3D11DeviceContext::ClearRenderTargetView takes a RGBA color for the background, but when i set the alpha value to 0, it is a black background. this is normal behaviour, as windows cant be transparent withour small modifications. SetLayeredWindowAttributes allows this, but you cant use those windows apis when you are using the xbox game bar. Is there a function just like that but for the xbox game bar? basically make a color x always be transaprent? Is that possible in uwp?

**Comment by totallymonkey** [comment]
Hello! When your widget is pinned and Game Bar is not showing in the foreground you should be able to see your transparency reflected. If you want to also have transparency while Game Bar is in the foreground you need to set the AllowForegroundTransparency property in your app manifest. You can find examples of this in the sample code.
Let me know if you are still having issues after looking into that!

**Comment by Spuckwaffel** [comment]
Thanks for the quick reply.
This is what my current xaml looks like and it is indeed transparent at the places where the swapchainpanal is not. (e.g on the right side. I am drawing onto the swapchainpanel with directX11 and whenever i draw something, i have to set a clear color for ClearRenderTargetView which is used as a "background color" to clear the drawings of the last frame. But as soon as i do that, the swapchainpanal is black because of the background color you have to set.
![image](https://user-images.githubusercontent.com/68144475/207712367-ab2d0f54-1d5e-4cf9-aace-f595f43a0126.png)
it looks like this:
![image](https://user-images.githubusercontent.com/68144475/207713302-162da52f-b325-4ee0-8411-268fb0acd4f8.png)
the swapchainpanal is filled with the color of the RenderTargetView background.
I have to somehow make a transparency key in my widget which will make a specific color transparent. How can i do that

**Comment by Spuckwaffel** [comment]
additional code:
this is my xaml page of the widget

```
DirectXPage::DirectXPage():
	m_windowVisible(true),
	m_coreInput(nullptr)
{
	InitializeComponent();

	m_main = std::unique_ptr<DirectXTestMain>(new DirectXTestMain(m_deviceResources));
	m_main->StartRenderLoop();

}
```

and here starts the real directX rendering:
```
void DirectXTestMain::StartRenderLoop()
{
	// If the animation render loop is already running then do not start another thread.
	if (m_renderLoopWorker != nullptr && m_renderLoopWorker->Status == AsyncStatus::Started)
	{
		return;
	}

	// Create a task that will be run on a background thread.
	auto workItemHandler = ref new WorkItemHandler([this](IAsyncAction ^ action)
	{
		// Calculate the updated frame and render once per vertical blanking interval.
		while (action->Status == AsyncStatus::Started)
		{
			critical_section::scoped_lock lock(m_criticalSection);
			Update();
			if (Render())
			{
				m_deviceResources->Present();
			}
		}
	});

	// Run task on a dedicated high priority background thread.
	m_renderLoopWorker = ThreadPool::RunAsync(workItemHandler, WorkItemPriority::High, WorkItemOptions::TimeSliced);
}
```

and here after i finished rendering i have to set a cleat color.
```
// Renders the current frame according to the current application state.
// Returns true if the frame was rendered and is ready to be displayed.
bool DirectXTestMain::Render() 
{
	// Don't try to render anything before the first Update.
	if (m_timer.GetFrameCount() == 0)
	{
		return false;
	}

	auto context = m_deviceResources->GetD3DDeviceContext();

	// Reset the viewport to target the whole screen.
	auto viewport = m_deviceResources->GetScreenViewport();
	context->RSSetViewports(1, &viewport);

	// Reset render targets to the screen.
	ID3D11RenderTargetView *const targets[1] = { m_deviceResources->GetBackBufferRenderTargetView() };
	context->OMSetRenderTargets(1, targets, m_deviceResources->GetDepthStencilView());

	DirectX::XMVECTORF32 ClearCol = { { { 0.0f, 0.0f, 0.0f, 0.0f } } }; <---------
	// Clear the back buffer and depth stencil view.
	context->ClearRenderTargetView(m_deviceResources->GetBackBufferRenderTargetView(), ClearCol);
	//context->ClearDepthStencilView(m_deviceResources->GetDepthStencilView(), D3D11_CLEAR_DEPTH | D3D11_CLEAR_STENCIL, 1.0f, 0);

	// Render the scene objects.
	m_fpsTextRenderer->Render();

	return true;
}
```
and this results into a black block

**Comment by Spuckwaffel** [comment]
update: fixed:
swapChainDesc.AlphaMode has to be set to DXGI_ALPHA_MODE_PREMULTIPLIED. everything is now transparent. thanks

**Comment by totallymonkey** [comment]
Awesome, glad to hear you got it figured out!
