### ISSUE TITLE
Transparency for custom widgets

### ISSUE THREAD

**Issue by VodBox** [microsoft/XboxGameBarSamples#38]
**Is your feature request related to a problem? Please describe.**
For a widget I'm working on, a common use for it will involve it being pinned over top of a game, but since widgets can't be transparent, the area taken up by our widget will completely obscure that area of the screen. Any attempt to adjust opacity of controls just reveals a white background.

**Describe the solution you'd like**
The solution we would like to see is to let us have the option to remove the background for the frame so that we can have control over the transparency of our widget and its controls, like the Performance widget already does.

**Describe alternatives you've considered**
We could not come up with any alternatives. Either the widget has transparency and doesn't obscure part of the screen, or it doesn't have transparency.

**Additional context**
Example of the Performance widget's transparency. ![](https://i.imgur.com/kmNzPP4.png)

We do know that the widget does not become a part of the Game Bar layout, and is instead a remote view. We confirmed that opacity changes in the Game Bar layout through debugging also affect the white background. Additionally we confirmed that our widget does not contain a background as part of it's layout that could explain the white background. This leads us to suspect that the remote view does not support an alpha channel.

**Comment by hamiltonia** [comment]
We're evaluating how to enable this functionality, but haven't committed to a date for delivery.

**Comment by hamiltonia** [comment]
Today we're publishing the prerelease version of the 20.06 release which includes support for transparency. Check out the [changelog](https://docs.microsoft.com/en-us/gaming/game-bar/changelog) for more information, along with the accompanying documentation. The samples for this early look are in the origin/prerelease branch. Be sure to update your Game Bar build with the latest from the SDK flight ring.

**Comment by hamiltonia** [comment]
FYI - the 20.06 release date has been tentatively moved to 6/24 in order to work through a recently discovered issue. Please continue to hold any app submissions that depend on the 5.3 SDK until it has been released.

Sorry for the inconvenience.
