### ISSUE TITLE
[SDK BUG] Using TryResizeWindowAsync when Game Bar is pinned only is broken

### ISSUE THREAD

**Issue by VodBox** [microsoft/XboxGameBarSamples#48]
**Describe the bug**
If you have a pinned widget and Game Bar's display mode is currently PinnedOnly, calling TryResizeWindowAsync will resize the widget, but not the clipping region. As such, if the widget is made smaller, the now blank region will still not let you click through, and if you make the widget bigger, the expanded region is not visible.

**To Reproduce**
1. Have a widget which is pinnable and can call TryResizeWindowAsync.
2. Pin widget and close Game Bar.
3. Perform an action with it that will call "TryResizeWindowAsync".
4. If made smaller, try clicking a region where the widget used to occupy.

**Expected behavior**
The expected behavior is that resizing my widget will result in the rendering and interactive region changing to that size, even when pinned. Currently it only behaves this way if Game Bar's Display Mode is Visible.

**Screenshots**
![](https://i.imgur.com/MpAO09x.gif)

**Desktop (please complete the following information):**
- OS version: Windows 10 1909 (OS Build 18363.778)
- Game Bar version: 5.120.4062.0
- SDK version: XboxGameBar.5.1.200402003

**Additional context**
There seems to be a related problem where sometimes if you hit "Restart" on "Something went wrong with this widget" while it's pinned, or when the widget enters that state after having been resized during running, the window position/size will change slightly, but the clipped region also remains the same, however I do not have reliable reproduction steps for this.

**Comment by hamiltonia** [comment]
Thanks - will track for the 20.06 release. [VSO 26048604]

**Comment by VodBox** [comment]
Just tested with the prerelease SDK (5.3.2005.12001.0-prerelease), and all attempts to call TryResizeWindowAsync, including in the samples, there is an winrt::hresult_error exception firing with `WinRT originate error - 0x8000001F` and the call fails. I don't know whether this should have it's own issue, or is just related to the efforts to fix this issue, and should be kept here.

**Comment by hamiltonia** [comment]
This issue is still active - we will continue to release updates prior to the 20.06 build being final.

**Comment by vidager** [comment]
That latest build in the SDK flight ring and the latest nuget should have these issues resolved. Please give it a try.

Nuget:
https://www.nuget.org/packages/Microsoft.Gaming.XboxGameBar/5.3.200522001-prerelease

Same matching build of Game Bar from the Game Bar SDK flight ring.

**Comment by hamiltonia** [comment]
This issue is resolved in the current 20.06 flighting builds and will be available for GA in ~2 weeks. Closing this issue now, please reactivate or comment if you're still seeing the issue.

**Comment by WizardCM** [comment]
I can confirm that the new build `5.3.200522001-prerelease` fixes the crash, but it doesn't seem to fix the resizing bug when pinned.

**Comment by totallymonkey** [comment]
Can you let me know which version of Game Bar you are running? The version you mentioned, is that just for the nuget package version?

**Comment by WizardCM** [comment]
Ah, my apologies for not including it. `5.320.5221.0` is the Game Bar version. The version above is the NuGet package version, yes.

**Comment by totallymonkey** [comment]
No problem. I'm seeing this work with that build of Game Bar and our sample apps. Can you provide more details about how are you calling the API to resize your window? And just to clarify you are still seeing the issue where the space the widget used to occupy is taking the mouse input instead of going to the app behind?

**Comment by WizardCM** [comment]
Happy to.

Video: [Streamable](https://streamable.com/cto2dl) ([mirror](http://file.wzd.li/2020-06-04_17-29-57.mp4))

You can see the **expand** action remain incorrectly cropped at 0:11, where cursor events do not go through the area where the widget should be. The difference compared to originally is that when the Game Bar is made visible at 0:21, there is an outline of where the widget should be, and attempting to resize it "fixes" the view.

The opposite issue occurs at 0:33, where **collapsing** the widget doesn't resize it properly - when the Game Bar is made visible at 0:35, it's clear the gadget didn't end up changing size in the first place (but our other code to hide the buttons/sliders worked correctly). Hiding the Game Bar then displays the shorter height (with the cursor passing through correctly) with the incorrect internal height.


This is in a Debug build.

Collapse on `Checked` event for `ToggleButton`:
```cpp
preCollapseHeight = ActualHeight();
m_widget.TryResizeWindowAsync(
		Size(ActualWidth(), 10 + StatusBar().ActualHeight() +
					    Preview().ActualHeight()));
```
Expand on `Unchecked` event for `ToggleButton`:
```cpp
m_widget.TryResizeWindowAsync(Size(ActualWidth(), preCollapseHeight));
preCollapseHeight = 0;
```

**Comment by totallymonkey** [comment]
The video is really helpful. I think I need more details on how your internal XAML content is laid out and how it reacts to the size changes. At 0:11 you are pressing the collapse button followed by the expand button. At that time, you are not seeing cursor events pass through where your widget should be rendered. This shows that Game Bar did the right thing and that it thinks your widget is now taller, but your content for some reason did not re-render properly. Can you give me more details on how you are manipulating your internal content during this? There may be some issue in how that's being done when Game Bar is in PinnedOnly mode that I'm not aware of.

Thanks!

**Comment by totallymonkey** [comment]
@WizardCM, I think we now have a local repro now. It's at least a very similar issue, so hopefully, we will be able to use that to get to the bottom of the behavior you are seeing.

**Comment by totallymonkey** [comment]
The latest build of Game Bar we pushed should address this: v5.320.6093.0
Could you try your scenario again and please report back if you are still seeing any issues?

**Comment by WizardCM** [comment]
> The latest build of Game Bar we pushed should address this: v5.320.6093.0
> Could you try your scenario again and please report back if you are still seeing any issues?

I can confirm v5.320.6093.0 fixes this issue. Huzzah!

**Comment by totallymonkey** [comment]
Excellent, thanks for reporting back!

**Comment by hamiltonia** [comment]
FYI - the 20.06 release date has been tentatively moved to 6/24 in order to work through a recently discovered issue. Please continue to hold any app submissions that depend on the 5.3 SDK until it has been released.

Sorry for the inconvenience.
