### ISSUE TITLE
[SDK BUG] Gamebar resizes preferences window to a different size than specified

### ISSUE THREAD

**Issue by lhak** [microsoft/XboxGameBarSamples#56]
**Describe the bug**

After a recent gamebar update, a preferences window will be resized to a size different from what is specified in the manifest.

**To Reproduce**
1. Open the WidgetAvSampleCs sample
2. Change the size of the preferences window in the manifest to something different (e.g. the height to 600)
3. Open the widget in the gamebar and click on the preferences button
4. The window will be opened at the correct size for a split second but will then will be resized

**Expected behavior**
The window size should follow the size defined in the manifest

**Screenshots**

**Desktop (please complete the following information):**
- OS version: Windows 10 2004 (19041.264)
- Game Bar version 5.320.5221.0
- SDK version: XboxGameBar.5.1.200402003

**Additional context**

**Comment by hamiltonia** [comment]
We're investigating this now.

**Comment by hamiltonia** [comment]
We'll be addressing this in the next update, should be available early next week.
VSO 26769630

**Comment by totallymonkey** [comment]
Please try the latest Game Bar build we have pushed to SDK Insiders: v5.320.6093.0
This issue should be addressed now.

**Comment by lhak** [comment]
The issue has been fixed. Thank you!

**Comment by hamiltonia** [comment]
FYI - the 20.06 release date has been tentatively moved to 6/24 in order to work through a recently discovered issue. Please continue to hold any app submissions that depend on the 5.3 SDK until it has been released.

Sorry for the inconvenience.
