### ISSUE TITLE
[SDK BUG] MinWindowSize/MaxWindowSize works unexpectedly

### ISSUE THREAD

**Issue by BloodmageThalnos** [microsoft/XboxGameBarSamples#58]
**Describe the bug**
MinWindowSize function do not work expectedly, and MaxWindowSize function makes the program crash.

**To Reproduce**
1. Clone and build **WidgetAdvSample**
2. Debug in x64 mode; Win+G
3. Click on SetMinWindowSize (behavior 1)
4. Click on SetMaxWindowSize (behavior 2)

**Behavior & Screenshots**
1. after MinWindowSize({800, 600}), the window can be resized to very small.
![gamebar1](https://user-images.githubusercontent.com/28505284/84088449-19190680-aa1f-11ea-95a6-6becf7b55af3.jpg)
2. after MaxWindowSize, nothings happens. But when you try to resize or drag the window, the whole game bar crashed (how can i get the crash log?).

**Desktop:**
- OS version: Windows 10 2004 build 19041.264
- Game Bar version  5.320.5291.0
- SDK version: XboxGameBar v5.1.200401003
- Target platform version: Windows 10.0.19041.0  (Tried 10.0.17763.0 also)

**Comment by hamiltonia** [comment]
Should be fixed in the current 20.06 release - please let us know if you're still seeing this.

**Comment by visionarylab** [comment]
@hamiltonia What is the fix. Any fixed sized for the Widget etc.

**Comment by hamiltonia** [comment]
The fix was internal to Game Bar and the SDK.
