### ISSUE TITLE
[SDK BUG] XboxGameBarWebAuthenticationBroker Fails With CallbackUri Containing "ms-app://"

### ISSUE THREAD

**Issue by moudis** [microsoft/XboxGameBarSamples#63]
**Describe the bug**
While attempting to use `XboxGameBarWebAuthenticationBroker` to authenticate with a third-party OAuth2 endpoint, I received uncaught exceptions with the following message:
```
Exception thrown: 'System.ArgumentException' in System.Private.CoreLib.dll
An exception of type 'System.ArgumentException' occurred in System.Private.CoreLib.dll but was not handled in user code
Value does not fall within the expected range.
```
With the stack trace:
```
 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PackageName.MainPage.<button_Click>d__4.MoveNext() in C:\Users\moudi\source\repos\PackageName\PackageName\MainPage.xaml.cs:line 49
```

Using the regular UWP `WebAuthenticationBroker` does work with my game bar widget, but the UI behavior is erratic. Clicking a button that calls `AuthenticateAsync` will minimize the Game Bar, and not always succeed in launching a webview.

`XboxGameBarWebAuthenticationBroker` doesn't seem to have documentation available anywhere other than its usage in the sample code in this repo, so I may be setting it up or using it incorrectly.

**To Reproduce**
* Initialize an instance of `XboxGameBarWebAuthenticationBroker` in an application.
* Create a `System.Uri` instance containing a URL for the broker to navigate to. My application is attempting to authenticate with the Bungie API for example, using `https://www.bungie.net/en/OAuth/Authorize?client_id=<snip>&state=random&response_type=code`
* Call AuthenticateAsync, such as the following:
```c#
XboxGameBarWidget _widget; // Initialized in OnActivated
var broker = new XboxGameBarWebAuthenticationBroker(_widget);
var resp = await _broker.AuthenticateAsync(XboxGameBarWebAuthenticationOptions.None, authUri, WebAuthenticationBroker.GetCurrentApplicationCallbackUri());
```
* The call will succeed with a `callbackUri` parameter using any scheme other than `ms-app://`, from my testing. Authentication will fail, as the application has no other way to receive the callback.

**Expected behavior**
Behavior similar to the `WebAuthenticationBroker` class. `WebAuthenticationBroker.AuthenticateAsync` uses the `ms-app:` scheme by default for its callback URI when one is not provided.

**Desktop (please complete the following information):**
- OS version: Windows 10 2004 (OS Build 19041.329)
- Game Bar version 5.320.6122.0
- SDK version: XboxGameBar.5.3.200605002

**Additional Context**
I did attempt to define a custom protocol handler (e.g. set `<uap:Extension Category="windows.protocol">` and handle URI activation in my widget), but I instead get the following exception:
```
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
An exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code
The specified protocol is unknown. (Exception from HRESULT: 0x800C000D)
```

**Comment by totallymonkey** [comment]
Thanks for reporting this issue, we will be investigating it soon

**Comment by joshhunt** [comment]
@moudis I experienced this as well - XboxGameBarWebAuthenticationBroker does not seem to support schemes other than http/s.

I was able to get it to work by having the redirect url be a valid https url that loads -  the auth broker will detect when this URL is hit and then return the code.

**Comment by moudis** [comment]
@joshhunt Thanks for the advice. :)

The behavior there is pretty surprising, but I guess it does more or less mirror what the UWP `WebAuthenticationBroker` does when given a callback URI. It looks like it checks the 302 Redirect given by the OAuth2 endpoint with the provided callback URI and considers the authentication passed if the two match and a code is returned. In my instance, setting the callback in my application configuration to `https://127.0.0.1` (both locally and on Bungie's website) does cause the authentication to succeed if the provided credentials are correct. I did start a `ncat` listener just to confirm it doesn't actually attempt to follow the callback, and it doesn't seem to.

It looks like this might not be a bug after all, just a misunderstanding on how the API is intended to work.

**Comment by totallymonkey** [comment]
It's true we didn't attempt to support other schemes besides http/s for our implementation. If you are not satisfied with this and can't achieve your goals with your widget, feel free to re-open the issue and we can look into adding more support. Thanks!
