### ISSUE TITLE
[ERROR] While building app packages: Manifest references file 'Microsoft.Gaming.XboxGameBar.dll' which is not part of the payload

### ISSUE THREAD

**Issue by sliptrixx** [microsoft/XboxGameBarSamples#73]
I believe I have followed all of documentation steps to port my app to the gamebar. It works just fine in bot debug and release mode. But I get this issue where the Microsoft.Gaming.XboxGameBar.dll cannot be found and not added to the package when I try to build an app bundle package for the Microsoft store. I have searched around and I cannot find a solution to it. Any help is appreciated.

**Comment by totallymonkey** [comment]
Are you able to create a package for the store with our samples? If you can, maybe you could send me a sample project with the issue you are seeing so I can investigate. Thanks!

**Comment by sliptrixx** [comment]
I tried running the sample and it worked without any errors after it automatically installed the nuget packages. I went ahead and tried it on my app, and it suddenly stopped throwing errors. Thank you for the help by the way. I'm still not sure what caused the issue. I'll go ahead and close the issue.

**Comment by totallymonkey** [comment]
Glad to hear it's working for you!
