### ISSUE TITLE
[SDK BUG] Cannot type with v5.3

### ISSUE THREAD

**Issue by dynamiquel** [microsoft/XboxGameBarSamples#75]
**Describe the bug**
When you have an app selected, and then you use a widget, you cannot type. This issue was not present with v5.1.

**To Reproduce**
1. Have a widget with text boxes.
2. Select an app, such as a web browser.
3. Open the Game Bar and try to type within the widget.

**Expected behavior**
Keyboard input should be sent to the widget.

**Desktop (please complete the following information):**
- OS version: Windows 10 1909 build 18363.959
- Game Bar version: 5.420.7201.0
- SDK version:  5.3.200605002

**Comment by totallymonkey** [comment]
I'm taking a look into this now

**Comment by totallymonkey** [comment]
Hey, so what is going on here is that your appxmanifest was missing the new entries needed for the latest version of the SDK.  The readme that pops up when you install the new version of the nuget has the entries you need, but I'll put them below as well. I verified by building your project that everything appears to be working with these entries. We will look into how we can make it more clear that this step needs to happen every time the SDK version is upgraded, or have something at runtime that would make it obvious they are missing. Please let me know if you see any other issues after adding these entries!

        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarWidgetAuthHost" InterfaceId="DC263529-B12F-469E-BB35-B94069F5B15A" />
        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarWidgetControlHost" InterfaceId="C309CAC7-8435-4082-8F37-784523747047" />
        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarWidgetForegroundWorkerHost" InterfaceId="DDB52B57-FA83-420C-AFDE-6FA556E18B83" />
        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarWidgetForegroundWorkerPrivate" InterfaceId="42BACDFC-BB28-4E71-99B4-24C034C7B7E0" />
        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarNavigationKeyCombo" InterfaceId="5EEA3DBF-09BB-42A5-B491-CF561E33C172" />
        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarWidgetActivatedEventArgsPrivate" InterfaceId="782535A7-9407-4572-BFCB-316B4086F102" />
        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarWidgetHost" InterfaceId="5D12BC93-212B-4B9F-9091-76B73BF56525" />
        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarWidgetHost2" InterfaceId="28717C8B-D8E8-47A8-AF47-A1D5263BAE9B" />
        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarWidgetPrivate" InterfaceId="22ABA97F-FB0F-4439-9BDD-2C67B2D5AA8F" />
        <Interface Name="Microsoft.Gaming.XboxGameBar.Private.IXboxGameBarWidgetPrivate2" InterfaceId="B2F7DB8C-7540-48DA-9B46-4E60CE0D9DEB" />

**Comment by dynamiquel** [comment]
Ok. Thank you.

**Comment by totallymonkey** [comment]
Just an FYI we are looking into having this step automated as part of the build.
