### ISSUE TITLE
Controller Support, Switch between widgets

### ISSUE THREAD

**Issue by Lucifer1662** [microsoft/XboxGameBarSamples#76]
Hello, I having an issue with integrating controller support with my widget.

My problem is that when using a controller and being focused on some part of the game bar UI external to my app, eg Widget Menu, I cannot use my controller to get back my widget/ any of the samples you have provided however I know this is possible as Xbox Social or Capture can be navigated into. (When i first open my app it has focus and i can navigate around with my controller, the problem occurs once the app has lost focus, by moving away from it).

Before
![image](https://user-images.githubusercontent.com/24789887/89013054-9180b180-d356-11ea-9c51-1e6d78e53726.png)

The goal, but for my own app.
![image](https://user-images.githubusercontent.com/24789887/89013146-b8d77e80-d356-11ea-816d-10c3ea2be190.png)

**Comment by totallymonkey** [comment]
Thanks for your feedback. Controller support is something we are looking to improve in the future. An easier way to get back to your widget with controller is to use the left or right trigger buttons, which will quickly cycle focus through the open widgets. Once you get to your widget, navigating down should take you in to your widget.

**Comment by totallymonkey** [comment]
Just wanted to give you another update. I did figure out what is causing the controller to not work at all and will get a fix in for the next release of Game Bar. It still doesn't make it perfect, but it at least works somewhat, unlike now.

**Comment by visionarylab** [comment]
Great to hear that. But mostly because they wanna give "priority" to Game rather than Game Bar Widget.
What the scenario on XBOX, does the game pause or game not pause, and
 user must click another non game key to let game controller to select any Game Bar Widget?

**Comment by Lucifer1662** [comment]
Sorry i think I may have not been clear in the question. The screen shots are from a windows PC, not an XBOX.

**Comment by totallymonkey** [comment]
This should be fixed now. Please let us know if you are still having any problems and open a new issue if you are. Thanks!
