### ISSUE TITLE
[QUESTION] Is there an event which says when the xbox gamebar is opened or closed?

### ISSUE THREAD

**Issue by sliptrixx** [microsoft/XboxGameBarSamples#77]
I noticed that the event `WindowsStateChanged` only gets triggered when the widget is launched or closed. Is there an event that I can subscribe to, which triggers a reload function every time the Xbox gamebar is opened by pressing WIN + G. This could be useful to pause background processing as well.

**Comment by Dawider10** [comment]
`XboxGameBarWidget.GameBarDisplayModeChanged` is the event you are looking for.
https://docs.microsoft.com/en-us/gaming/game-bar/api/xgb-widget

**Comment by sliptrixx** [comment]
Nevermind, there's this event called `XboxGameBarWidget.VisibleChanged` which does the exact same thing. `XboxGameBarWidget.Visible` is a bool that says if the widget is visible to the user display or not.

**Comment by Dawider10** [comment]
> Nevermind, there's this event called `XboxGameBarWidget.VisibleChanged`

Yeah, and this is probably better for your application as it shouldn't trigger when you close Game Bar while the widget is pinned.
