### ISSUE TITLE
This is close to the greatest recording software known to man.. except

### ISSUE THREAD

**Issue by bobsangry** [microsoft/XboxGameBarSamples#78]
Where is 1. My volume levels for my mic? 
and 2. more importantly and the purpose of this entire feedback... 
CAN I GET A NOISE GATE PLEASE?? 

**Is your feature request related to a problem? Please describe.**
The problem is when I'm not talking .. you can hear the static in the room 

**Describe the solution you'd like**
Just need either a widget or a function built in to add a noise gate on your microphone...

**Describe alternatives you've considered**
Recording my audio seperately in my DAW.. Works but crazy long process plus lining up plus many errors and things can go wrong from here to there.. 
Tried Muffling the sound of my pc.. Rediculously impossible.. 
TRIED getting a whole NEW recording software even though this ones damn near perfect..
Why cant yall just add a quick feature? 

**Additional context**
I think I've made my point Thanks for listening and hopefully solving this =)

Much love~

**Comment by visionarylab** [comment]
- Allow API access to manipulate sound stream for microphone manufacture?

**Comment by hamiltonia** [comment]
I've filed a bug directly against Game Bar for this, closing this issue as this is not directly related to the SDK.

VSO 29138874
