### ISSUE TITLE
[BUG] Sample Package.appxmanifest, does not describe as it is.

### ISSUE THREAD

**Issue by visionarylab** [microsoft/XboxGameBarSamples#79]
**Describe the bug**
XboxGameBarSamples/Samples/WidgetAdvSampleCS/Package.appxmanifest
Line 45 and 75, both two extension having a swap?

**To Reproduce**
1. Go to 'XboxGameBarSamples/Samples/WidgetAdvSampleCS/Package.appxmanifest'
2. Widget1 and Widget1Settings is no what they mean.

**Expected behavior**
Swap Widget1 and Widget1Settings

**Comment by hamiltonia** [comment]
Hi @visionarylab - it's not clear to me what you're reporting here. Widget1 is the primary widget opened, Widget1Settings is the widget which is opened when using the settings button in the title bar of Widget1. Are you reporting that the description of what they are is not clear? Not sure what you would want swapped.

**Comment by visionarylab** [comment]
Sorry, yes when clicking the Widget Advances CS 1 from home menu it show a long windows (With ActiveAsync, and other pinned status etc, that could be designed to use as WidgetSettings sample) instead same size windows as Widget 2 (Widget Advances CS 2 )

It is not a bug, it is just weird when you clicking setting button of widget1, it show an empty small windows with clicked button
