### ISSUE TITLE
[Question] How to setup RestrictedSample. I can do sample code on same solution, but not on new project.

### ISSUE THREAD

**Issue by edwardchanjw** [microsoft/XboxGameBarSamples#82]
**Describe**

**To Reproduce**
1. Copy RestrictedSamples's widget to WidgetAdvSampleCS's widget1 and widget2..
a. Update NETCore.UniversalWindowsPlatform nuget to 1 more version. WidgetAdvSampleCS is one version behind
b. Copy Extensions\DispatcherTaskExtensions
c. Copy widget1 class entirely

**Expected behavior**
1. The file picker should not crashed...
2. If Debug it is 

```
 System.UnauthorizedAccessException
  HResult=0x80070005
  Message=Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

```
**Additional context**
I am no sure, I feeling kinda stupid to even merge two sample.
Any other config/setting or nuget update need to be done?
[The project's solution Link ](https://github.com/edwardchanjw/xboxgamebar_restricted)

Probably I doing wrong with these? But I haven click the widget 1's file picker and never clean it, before clicking widget2's file picker
// Also, at this time you should let the XboxGameBarForegroundWorker object fall out of scope, as it is only allowed to be used once

**Comment by totallymonkey** [comment]
Hi @edwardchanjw,

The restricted API's can only be called from apps who's PFN we have whitelisted within Game Bar. Because of this it will only work in the restricted sample. Can you explain what you are trying to accomplish? I'd be happy to help you out!

**Comment by edwardchanjw** [comment]
@totallymonkey I see. Even I do it within Restricted sample, I copied the widget1 to widget2. The second Widget won't work. Actually I am just wanna develop some widget into one solution. (Notepad, Graphic Capture, Video player). At least 2 or more needed the restricted sample. (File Picker, Graphic Capture). 

If there is more important roadmap then all these relaxing workflow can be discussed when communities is growing.

**Comment by totallymonkey** [comment]
When you copy widget1 to widget2, what doesn't work in that case? Are you getting the UnauthorizedAccess exception, or is something else going on?

The reason the file picker sample is restricted is because of the slight complexity to implementing it properly and we want  developers to really think through whether or not such a disruptive experience is needed in their widget. If that's the case, then we can work with you to make sure that it is all working correctly.

**Comment by edwardchanjw** [comment]
@totallymonkey I am no sure whether I am copying right or not. It is following error, but both widget 1 and widget 2 is having the filepicker code. First widget working fine, but when clicking on second widget's file picker crash. Even you click second widget's file picket at first, also crashed.

```
 System.UnauthorizedAccessException
  HResult=0x80070005
  Message=Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>
```

**Comment by totallymonkey** [comment]
@edwardchanjw, ah, ok. I double checked and we actually have to allow specific widgets (Not just the widget package) to call these API's so in the sample only Widget1 was allowed to call. Hope that clears that up for you.

**Comment by totallymonkey** [comment]
@edwardchanjw We added a reg key you can set to enable calling the restricted API from any widget for testing/development purposes.

Please try adding the following key to this location:
Software\Microsoft\GameBar
DevFeatures (Set to 1)

**Comment by vidager** [comment]
Closing since there hasn't been activity since Oct 7 and it appears totallymonkey gave a workaround for development.  If you have need to ship a widget with a Restricted API, you can reach out to us to add your widget to the allow list. 

Thanks!
Ben

**Comment by edwardchanjw** [comment]
@totallymonkey  @vidager  That good enough and transparent. Well done Microsoft folk
