### ISSUE TITLE
[Question] window not pinning

### ISSUE THREAD

**Issue by doubletoker** [microsoft/XboxGameBarSamples#91]
I'm wondering if there is something more to pinning, than just setting `<PinningSupported>true</PinningSupported>` and inside gamebar clicking the pin, cause mine is not pinning at all, I'm able to pin performance, but for some reason mine is not pinning.
any help would be appreciated.

**Comment by totallymonkey** [comment]
Hello,
Are you seeing the pin button show up and it just isn't staying up when going into PinnedOnly mode? Or are you not seeing the pin button show up on your widget at all?

**Comment by doubletoker** [comment]
I'm seeing the pin button, but it's not staying up when the pin is solid.

**Comment by totallymonkey** [comment]
Do the samples work for you? Could you make a small sample project that reproduces the issue you are seeing so I could take a look?

**Comment by doubletoker** [comment]
I haven't tried the samples, I was just reading the docs trying to set it all up myself from scratch. I also notice, that when I do make the pin solid, and switch back to the app, the area where the window was, seems to be blocking mouse clicks, which I think might be wrong to, cause it's supposed to enable click through. anyway  I added a project of what I currently have, it's at https://github.com/doubletoker/kemu if you would take a look and help me figure it out, I'd appreciate the effort. I'm just trying to learn what step I'm missing, with the blocking of the mouse clicks, I was thinking maybe it's a draw issue? who really knows though, thanks.

**Comment by doubletoker** [comment]
alright my bad, it's a combination of problems all on me. at one point when it wasn't displaying, I tried to make the constructor for the widget default, so it didn't call InitializeComponet, and also I was trying to use directx and I was using a swapchainpanel before I initialized and painted the first screen, inside gamebar, it was black when it loaded in game bar, so I assumed it would be black still when I pinned and clicked out of it, but that panel is transparent, and the click through stuff, was because I clicked to disable click through, thanks for everything though.

**Comment by totallymonkey** [comment]
Glad to hear you got it sorted!
