### ISSUE TITLE
[Question] Application activation for a VB project?

### ISSUE THREAD

**Issue by Viroscope** [microsoft/XboxGameBarSamples#92]
I have an application that I am trying to make for the XboxGameBar and as a standalone application it works great. when I use the game bar to open the widget the window opens like it is supposed to but the WebView (only thing on it atm) just spins and never works.

I am assuming this is related to the way that VB uses it's sub classes to load the form and such ex. Protected Overrides Sub OnLaunched

Is their a way to activate a VB project properly? I see that for C++ it wants you to use OnActivated

**Comment by totallymonkey** [comment]
Hello,

I remember getting a VB project to work in the past. Someone on the team can investigate this issue and get back to you. By any chance, can you share the sample project you are using?

**Comment by vidager** [comment]
Hi Viroscope,

You should be able to use VB, but we don't have any samples to share. With that said, you will need the exact same methods/calls that you need for C# but in VB syntax.  Both VB and C# will use the .NET flow, so please use C# as your guide.

Yes, Game Bar widgets are activated via OnActivated, not OnLaunched.  You should be able to follow the development guide here: https://docs.microsoft.com/en-us/gaming/game-bar/. 

Thanks!
Ben
